/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;
import model.Account;
import sevice.AccountService;

/**
 *
 * @author Acer
 */
public class DN extends javax.swing.JFrame {

    /**
     * Creates new form DN
     */
    private AccountService service = new AccountService();
    
    public DN() {
        initComponents();
        labelSignUp.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                labelSignUp.setText("<html><u><font color='000080'>Sign up</font></u></html>");
            }
            
            @Override
            public void mouseExited(MouseEvent e) {
                labelSignUp.setText("<html>Sign up</html>");
            }
        });
        txtUserName.setBackground(new Color(0, 0, 0, 1));
        txtPassWord.setBackground(new Color(0, 0, 0, 1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblExit = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        labelSignUp = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        txtPassWord = new javax.swing.JPasswordField();
        disible = new javax.swing.JLabel();
        show = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        labelSignUp1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/fbw2.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(25, 118, 211));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblExit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblExit.setForeground(new java.awt.Color(255, 255, 255));
        lblExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit.setText("x");
        lblExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });
        jPanel2.add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 0, 30, 31));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LOGIN");
        jLabel2.setToolTipText("");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 461, 36));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("experience, from exquisite dishes to luxurious space.");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 455, 24));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("      Username");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 449, 22));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("      ___________________________________________________________________________");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 394, 20));
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 50, 20));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("     Password");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 443, 22));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("      ___________________________________________________________________________");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 276, 394, 30));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Forget Password ?");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
        });
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 115, 20));

        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(0, 102, 255));
        btnLogin.setText("LOGIN");
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 209, 35));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Don't have an account?");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 126, 20));

        labelSignUp.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        labelSignUp.setForeground(new java.awt.Color(255, 255, 255));
        labelSignUp.setText("Sign up");
        labelSignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelSignUpMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelSignUpMouseExited(evt);
            }
        });
        jPanel2.add(labelSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, 50, 20));

        txtUserName.setFont(txtUserName.getFont().deriveFont(txtUserName.getFont().getSize()+2f));
        txtUserName.setForeground(new java.awt.Color(255, 255, 255));
        txtUserName.setBorder(null);
        jPanel2.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 360, 30));

        txtPassWord.setFont(txtPassWord.getFont().deriveFont(txtPassWord.getFont().getSize()+2f));
        txtPassWord.setForeground(new java.awt.Color(255, 255, 255));
        txtPassWord.setBorder(null);
        jPanel2.add(txtPassWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 360, 30));

        disible.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                disibleMouseClicked(evt);
            }
        });
        jPanel2.add(disible, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 50, 50));

        show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showMouseClicked(evt);
            }
        });
        jPanel2.add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, -1, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText(" Prince Restaurant is proud to bring you a world-class culinary ");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 455, 24));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Don't have an account?");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 126, 20));

        labelSignUp1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        labelSignUp1.setForeground(new java.awt.Color(255, 255, 255));
        labelSignUp1.setText("Sign up");
        labelSignUp1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelSignUp1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelSignUp1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelSignUp1MouseExited(evt);
            }
        });
        jPanel2.add(labelSignUp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, 50, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 0, 470, 550));

        setSize(new java.awt.Dimension(1066, 551));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseEntered

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        // TODO add your handling code here:
        String userLogin = txtUserName.getText();
        String passLogin = Arrays.toString(txtPassWord.getPassword());
        if (userLogin.isEmpty() || passLogin.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không được để trống", "Login", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btnLoginMouseClicked

    private void labelSignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSignUpMouseClicked
        DK signUpFrame = new DK();
        signUpFrame.setVisible(true);
        signUpFrame.pack();
        this.dispose();
    }//GEN-LAST:event_labelSignUpMouseClicked

    private void labelSignUpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSignUpMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_labelSignUpMouseExited

    private void disibleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disibleMouseClicked
        // TODO add your handling code here:
        txtPassWord.setEchoChar((char) 0);
        disible.setVisible(false);
        disible.setVisible(false);
        show.setEnabled(true);
        show.setEnabled(true);
    }//GEN-LAST:event_disibleMouseClicked

    private void showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMouseClicked
        // TODO add your handling code here:
        txtPassWord.setEchoChar((char) 8226);
        disible.setVisible(true);
        disible.setVisible(true);
        show.setEnabled(false);
        show.setEnabled(false);
    }//GEN-LAST:event_showMouseClicked

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String user = txtUserName.getText();
        String pass = txtPassWord.getText();
        if (user.isBlank() || pass.isBlank()) {
            JOptionPane.showMessageDialog(this, "Không được để trống các trường");
            return;
        }
        List<Account> list = service.getAll();
        for (Account o : list) {
            if (o.getUserName().equals(user) && o.getPass().equals(pass)) {
                if (o.getRole() == 0) {
                    JOptionPane.showMessageDialog(this, "CHÀO MỪNG KHÁCH HÀNG ĐÃ ĐẾN VỚI NHÓM 3");
                }
                if (o.getRole() == 1) {
                    JOptionPane.showMessageDialog(this, "CHÀO MỪNG NHÂN VIÊN ĐÃ ĐẾN VỚI NHÓM 3");
                }
                if (o.getRole() == 2) {
                    JOptionPane.showMessageDialog(this, "CHÀO MỪNG QUẢN LÝ ĐÃ ĐẾN VỚI NHÓM 3");
                }
                this.setVisible(false);
                ViewGiaoDien v = new ViewGiaoDien();
                v.setVisible(true);
                return;
            }
        }
        JOptionPane.showMessageDialog(this, "Tài khoản hoặc mật khẩu sai");
    }//GEN-LAST:event_btnLoginActionPerformed

    private void labelSignUp1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSignUp1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelSignUp1MouseClicked

    private void labelSignUp1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSignUp1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_labelSignUp1MouseExited

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        QMK view = new QMK();
        view.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel disible;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelSignUp;
    private javax.swing.JLabel labelSignUp1;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel show;
    private javax.swing.JPasswordField txtPassWord;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
