/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bai3.sinhvien;

import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NGUYEN THI THU NGHIA
 */
public class ViewSinhVien extends javax.swing.JFrame {

    /**
     * Creates new form ViewSinhVien
     */
    private SinhVienService_IMPL service = new SinhVienService_IMPL();
    private DefaultTableModel model = new DefaultTableModel();
    private int index = -1;//chưa chọn dòng dữ liệu nào

    public ViewSinhVien() {
        initComponents();
        this.setLocationRelativeTo(null);
        //đổ dữ liệu vào combo
        cboNganh.removeAllItems();//xóa sạch items cũ
        cboNganh.addItem("CNTT");
        cboNganh.addItem("UDPM");
        cboNganh.addItem("WEB");
        cboNganh.addItem("PTPM");
        this.fillTable(service.getAll());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblQLSV = new javax.swing.JLabel();
        lblHoten = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        lblDiem = new javax.swing.JLabel();
        txtHocluc = new javax.swing.JTextField();
        lblNganh = new javax.swing.JLabel();
        cboNganh = new javax.swing.JComboBox<>();
        lblHocluc = new javax.swing.JLabel();
        txtDiem = new javax.swing.JTextField();
        chkPhanthuong = new javax.swing.JCheckBox();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnCapnhat = new javax.swing.JButton();
        btnNhapmoi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSinhVien = new javax.swing.JTable();
        btnSxTen = new javax.swing.JButton();
        btnSxDiem = new javax.swing.JButton();
        btnTimkiem = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÍ SINH VIÊN");

        lblQLSV.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblQLSV.setForeground(new java.awt.Color(255, 0, 0));
        lblQLSV.setText("QUẢN LÍ SINH VIÊN");

        lblHoten.setText("Họ tên");

        txtHoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoTenActionPerformed(evt);
            }
        });

        lblDiem.setText("Điểm");

        txtHocluc.setEditable(false);
        txtHocluc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoclucActionPerformed(evt);
            }
        });

        lblNganh.setText("Ngành");

        cboNganh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblHocluc.setText("Học lực");

        txtDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiemActionPerformed(evt);
            }
        });

        chkPhanthuong.setText("Có phần thưởng");
        chkPhanthuong.setEnabled(false);

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnCapnhat.setText("Cập nhật");
        btnCapnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapnhatActionPerformed(evt);
            }
        });

        btnNhapmoi.setText("Nhập mới");
        btnNhapmoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapmoiActionPerformed(evt);
            }
        });

        tblSinhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "HỌ VÀ TÊN", "ĐIỂM", "NGÀNH", "HỌC LỰC", "THƯỞNG"
            }
        ));
        tblSinhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSinhVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSinhVien);

        btnSxTen.setText("Sx theo tên");
        btnSxTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSxTenActionPerformed(evt);
            }
        });

        btnSxDiem.setText("Sx theo điểm");
        btnSxDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSxDiemActionPerformed(evt);
            }
        });

        btnTimkiem.setText("Tìm kiếm theo tên");
        btnTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimkiemActionPerformed(evt);
            }
        });

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblHoten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNganh, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblHocluc, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkPhanthuong)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnCapnhat)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnNhapmoi))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cboNganh, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtHocluc, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(51, 51, 51)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnThoat)
                                            .addComponent(btnTimkiem)
                                            .addComponent(btnSxDiem)
                                            .addComponent(btnSxTen)))))
                            .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(lblQLSV, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblQLSV)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHoten)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSxTen))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiem)
                    .addComponent(txtDiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSxDiem))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNganh)
                    .addComponent(cboNganh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimkiem))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHocluc)
                    .addComponent(txtHocluc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThoat))
                .addGap(18, 18, 18)
                .addComponent(chkPhanthuong)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnXoa)
                    .addComponent(btnCapnhat)
                    .addComponent(btnNhapmoi))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoTenActionPerformed

    private void txtHoclucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoclucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoclucActionPerformed

    private void txtDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiemActionPerformed

    private void tblSinhVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSinhVienMouseClicked
        // TODO add your handling code here:
        index = tblSinhVien.getSelectedRow();//lấy ra dòng được chọn
        this.showSinhVien(index);
    }//GEN-LAST:event_tblSinhVienMouseClicked

    private void btnTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimkiemActionPerformed
        // TODO add your handling code here:
        String ten;
        ten = JOptionPane.showInputDialog(this, "Mời bạn nhập tên cần tìm: ");
        service.findTen(ten);
        this.fillTable(service.findTen(ten));
    }//GEN-LAST:event_btnTimkiemActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);// dừng chương trình đột ngột
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnSxDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSxDiemActionPerformed
        // TODO add your handling code here:
        service.sapXepDiem(service.getAll());
        this.fillTable(service.getAll());
    }//GEN-LAST:event_btnSxDiemActionPerformed

    private void btnSxTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSxTenActionPerformed
        // TODO add your handling code here:
        service.sapXepTen(service.getAll());
        this.fillTable(service.getAll());
    }//GEN-LAST:event_btnSxTenActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, service.addSV(this.readForm()));
        this.fillTable(service.getAll());
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnNhapmoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapmoiActionPerformed
        // TODO add your handling code here:
        // xóa trắng from
        txtHocluc.setText("");
        txtHoTen.setText("");
        txtDiem.setText("");
        cboNganh.setSelectedItem(0);//chọn item đầu tiên
        //xóa check box thưởng
        chkPhanthuong.setSelected(false);
    }//GEN-LAST:event_btnNhapmoiActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        index = tblSinhVien.getSelectedRow();
        JOptionPane.showMessageDialog(this, service.removeSV(index));
        this.fillTable(service.getAll());
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnCapnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapnhatActionPerformed
        // TODO add your handling code here:
        index = tblSinhVien.getSelectedRow();
        JOptionPane.showMessageDialog(this, service.updateSV(index, this.readForm()));
        this.fillTable(service.getAll());
    }//GEN-LAST:event_btnCapnhatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewSinhVien().setVisible(true);
            }
        });
    }

    void fillTable(List<SinhVien> list) {
        model = (DefaultTableModel) tblSinhVien.getModel();
        model.setRowCount(0);
        for (SinhVien sv : list) {
            model.addRow(sv.toDataRow());
        }
    }

    void showSinhVien(int index) {
        SinhVien sv = service.getAll().get(index);
        txtHoTen.setText(sv.getTen());
        txtDiem.setText(String.valueOf(sv.getDiem()));
        txtHocluc.setText(sv.getHocLuc());
        if (sv.getThuong())//mặc định là true thì chạy
        {//có thưởng
            chkPhanthuong.setSelected(true);
        } else {
            chkPhanthuong.setSelected(false);
        }
    }

    SinhVien readForm() {
        String ten, nganh;
        double diem;
        ten = txtHoTen.getText().trim();
        //trim(); cắt ký tự trắng ở đầu và cuối
        if (ten.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tên không được để rỗng");
            return null;//tạm dừng chương tình
        } else {//đã có dữ liệu tên
            if (!ten.matches("[a-zA-Z ]+")) {//không đúng mẫu
                JOptionPane.showMessageDialog(this, "Tên sai định dạng");
                return null;
            }
        }//đóng else
        nganh = cboNganh.getSelectedItem().toString();
        //
        if (txtDiem.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Chưa nhập điểm");
            txtDiem.setBackground(Color.yellow);
            return null;
        } else {
            try {
                diem = Double.parseDouble(txtDiem.getText());
                if (diem < 0 || diem > 10) {
                    JOptionPane.showMessageDialog(this, "Điểm sai dữ liệu");
                    return null;
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Điểm sai định dạng");
                return null;
            }
        }
        return new SinhVien(ten, diem, nganh);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapnhat;
    private javax.swing.JButton btnNhapmoi;
    private javax.swing.JButton btnSxDiem;
    private javax.swing.JButton btnSxTen;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTimkiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboNganh;
    private javax.swing.JCheckBox chkPhanthuong;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDiem;
    private javax.swing.JLabel lblHocluc;
    private javax.swing.JLabel lblHoten;
    private javax.swing.JLabel lblNganh;
    private javax.swing.JLabel lblQLSV;
    private javax.swing.JTable tblSinhVien;
    private javax.swing.JTextField txtDiem;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtHocluc;
    // End of variables declaration//GEN-END:variables
}
