/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bai2.demo;

import javax.swing.JOptionPane;

/**
 *
 * @author NGUYEN THI THU NGHIA
 */
public class DemoControl extends javax.swing.JFrame {

    /**
     * Creates new form DemoControl
     */
    public DemoControl() {
        initComponents();
        //1. Xóa hết items cũ trong combo box
        cbo_quequan.removeAllItems();
        //2. Thêm dữ liệu mới vào combo box
        cbo_quequan.addItem("Hà Nội");
        cbo_quequan.addItem("Thái Nguyên");
        cbo_quequan.addItem("Bắc Ninh");
        cbo_quequan.addItem("HCM");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lbl_Nhan1 = new javax.swing.JLabel();
        txtHoten = new javax.swing.JTextField();
        btn_Check = new javax.swing.JButton();
        btn_set = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_pass = new javax.swing.JLabel();
        pass_pass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        rdo_nam = new javax.swing.JRadioButton();
        rdo_nu = new javax.swing.JRadioButton();
        btn_radio = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        chk_tien = new javax.swing.JCheckBox();
        chk_thethao = new javax.swing.JCheckBox();
        chk_dulich = new javax.swing.JCheckBox();
        chk_hoccode = new javax.swing.JCheckBox();
        btn_checkbox = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cbo_quequan = new javax.swing.JComboBox<>();
        btn_checkQQ = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_Nhan1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbl_Nhan1.setForeground(new java.awt.Color(255, 0, 0));
        lbl_Nhan1.setText("DEMO CONTROL");

        btn_Check.setBackground(new java.awt.Color(204, 255, 255));
        btn_Check.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_Check.setForeground(new java.awt.Color(255, 0, 0));
        btn_Check.setText("CHECK");
        btn_Check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CheckActionPerformed(evt);
            }
        });

        btn_set.setBackground(new java.awt.Color(204, 153, 255));
        btn_set.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_set.setForeground(new java.awt.Color(255, 255, 255));
        btn_set.setText("Set");
        btn_set.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_setActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Giới tính:");

        txt_pass.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txt_pass.setText("Pass:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Họ tên người yêu: ");

        buttonGroup1.add(rdo_nam);
        rdo_nam.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rdo_nam.setText("Nam");
        rdo_nam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_namActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdo_nu);
        rdo_nu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rdo_nu.setSelected(true);
        rdo_nu.setText("Nữ");
        rdo_nu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_nuActionPerformed(evt);
            }
        });

        btn_radio.setBackground(new java.awt.Color(255, 102, 204));
        btn_radio.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_radio.setForeground(new java.awt.Color(255, 255, 255));
        btn_radio.setText("Check Radio");
        btn_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_radioActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Sở thích:");

        chk_tien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chk_tien.setText("Tiền");

        chk_thethao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chk_thethao.setText("Thể thao");

        chk_dulich.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chk_dulich.setText("Du lịch");
        chk_dulich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_dulichActionPerformed(evt);
            }
        });

        chk_hoccode.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chk_hoccode.setText("Học code");

        btn_checkbox.setBackground(new java.awt.Color(102, 204, 255));
        btn_checkbox.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_checkbox.setForeground(new java.awt.Color(255, 255, 255));
        btn_checkbox.setText("Check Box");
        btn_checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_checkboxActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Quê quán:");

        cbo_quequan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbo_quequan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbo_quequan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_quequanActionPerformed(evt);
            }
        });

        btn_checkQQ.setBackground(new java.awt.Color(204, 255, 255));
        btn_checkQQ.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_checkQQ.setForeground(new java.awt.Color(0, 153, 255));
        btn_checkQQ.setText("Check QQ");
        btn_checkQQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_checkQQActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Họ tên", "Giới tính", "Sở thích", "Quê quán"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(chk_tien, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(chk_thethao, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(chk_dulich, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(chk_hoccode, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(cbo_quequan, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(194, 194, 194)
                                            .addComponent(btn_checkQQ))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtHoten, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(pass_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(37, 37, 37)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(btn_checkbox)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btn_set)
                                                    .addComponent(btn_Check, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(rdo_nam, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(rdo_nu, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btn_radio)))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(lbl_Nhan1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Nhan1)
                    .addComponent(btn_Check, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHoten, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_set)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btn_checkbox))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_pass)
                            .addComponent(pass_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rdo_nam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rdo_nu))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                            .addComponent(chk_tien)
                            .addComponent(chk_thethao)
                            .addComponent(chk_dulich)
                            .addComponent(chk_hoccode))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbo_quequan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_checkQQ))
                        .addGap(98, 98, 98))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_radio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(188, 188, 188))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CheckActionPerformed
        // TODO add your handling code here:
        String ten, pass;
        ten = txtHoten.getText();//lấy dữ liệu từ text ra
        pass = pass_pass.getText();//lấy pass
        if (ten.equalsIgnoreCase("trang") && pass.equalsIgnoreCase("123")) {
            JOptionPane.showMessageDialog(this, "Dung du lieu");
        } else {
            JOptionPane.showMessageDialog(this, "Sai thong tin");
        }
    }//GEN-LAST:event_btn_CheckActionPerformed

    private void btn_setActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_setActionPerformed
        // TODO add your handling code here:
        txtHoten.setText("thunghia hehe");
    }//GEN-LAST:event_btn_setActionPerformed

    private void btn_radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_radioActionPerformed
        // TODO add your handling code here:
        if (rdo_nam.isSelected()) {
            JOptionPane.showMessageDialog(this, "Gioi tinh Nam");
        } else {
            JOptionPane.showMessageDialog(this, "Gioi tinh Nu");
        }
    }//GEN-LAST:event_btn_radioActionPerformed

    private void chk_dulichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_dulichActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk_dulichActionPerformed

    private void btn_checkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_checkboxActionPerformed
        // TODO add your handling code here:
        String soThich = "";
        if (chk_tien.isSelected()) {
            soThich = soThich + "thich tien";
        }
        if (chk_thethao.isSelected()) {
            soThich = soThich + "thich the thao";
        }
        if (chk_dulich.isSelected()) {
            soThich = soThich + "thich du lich";
        }
        if (chk_hoccode.isSelected()) {
            soThich = soThich + "thich hoc code";
        }
        if (soThich.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "May thich ngu voi giun");
        } else
            JOptionPane.showMessageDialog(this, soThich);
    }//GEN-LAST:event_btn_checkboxActionPerformed

    private void cbo_quequanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_quequanActionPerformed
        // TODO add your handling code here:
        cbo_quequan.removeAllItems();
        cbo_quequan.addItem("Hà Nội");
        cbo_quequan.addItem("Bắc Ninh");
        cbo_quequan.addItem("Thái Nguyên");
        cbo_quequan.addItem("Hồ Chí Minh");
    }//GEN-LAST:event_cbo_quequanActionPerformed

    private void btn_checkQQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_checkQQActionPerformed
        // TODO add your handling code here:
        String queQuan;
        queQuan = cbo_quequan.getSelectedItem().toString();
        JOptionPane.showMessageDialog(this, "Que quan la " + queQuan);
    }//GEN-LAST:event_btn_checkQQActionPerformed

    private void rdo_nuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_nuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdo_nuActionPerformed

    private void rdo_namActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_namActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdo_namActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DemoControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DemoControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DemoControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DemoControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DemoControl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Check;
    private javax.swing.JButton btn_checkQQ;
    private javax.swing.JButton btn_checkbox;
    private javax.swing.JButton btn_radio;
    private javax.swing.JButton btn_set;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbo_quequan;
    private javax.swing.JCheckBox chk_dulich;
    private javax.swing.JCheckBox chk_hoccode;
    private javax.swing.JCheckBox chk_thethao;
    private javax.swing.JCheckBox chk_tien;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_Nhan1;
    private javax.swing.JPasswordField pass_pass;
    private javax.swing.JRadioButton rdo_nam;
    private javax.swing.JRadioButton rdo_nu;
    private javax.swing.JTextField txtHoten;
    private javax.swing.JLabel txt_pass;
    // End of variables declaration//GEN-END:variables
}
