use QLDA
go
--1a
SELECT MADA, CAST(SUM(THOIGIAN) as DECIMAL(6,2)) as N'Thời gian' FROM PHANCONG
GROUP BY MADA

--1b
SELECT MADA, CAST(SUM(THOIGIAN) as VARCHAR(20)) as N'Thời gian' FROM PHANCONG
GROUP BY MADA

SELECT MADA,
CAST(SUM(THOIGIAN) as DECIMAL(6,2)) as N'Thời gian - DECIMAL',
CAST(SUM(THOIGIAN) as VARCHAR(20)) as N'Thời gian - VARCHAR'
FROM PHANCONG
GROUP BY MADA

--1c
SELECT PHONGBAN.MAPHG, PHONGBAN.TENPHG, AVG(LUONG) as N'Lương TB'
FROM PHONGBAN, NHANVIEN
WHERE PHONGBAN.MAPHG = NHANVIEN.PHG
GROUP BY PHONGBAN.MAPHG, PHONGBAN.TENPHG

--1d
SELECT PHONGBAN.MAPHG, PHONGBAN.TENPHG,
FORMAT(CONVERT(DECIMAL(10,2), AVG(LUONG)), '#,##0.00' ) as N'Lương TB'
FROM PHONGBAN, NHANVIEN
WHERE PHONGBAN.MAPHG = NHANVIEN.PHG
GROUP BY PHONGBAN.MAPHG, PHONGBAN.TENPHG

--1e
SELECT PHONGBAN.MAPHG, PHONGBAN.TENPHG,
FORMAT(CONVERT(DECIMAL(10,2), AVG(LUONG)), '#,##0.00' ) as N'Lương TB'
FROM PHONGBAN
inner join NHANVIEN on NHANVIEN.PHG = PHONGBAN.MAPHG
GROUP BY PHONGBAN.MAPHG, PHONGBAN.TENPHG

SELECT TENPHG, CONVERT(decimal(10,2), AVG(LUONG)) as N'Lương TB',
left(CONVERT(decimal(10,2), AVG(LUONG)),3) + 
replace(CONVERT(decimal(10,2), AVG(LUONG)),left(CONVERT(decimal(10,2), AVG(LUONG)),3),',')
FROM PHONGBAN
inner join NHANVIEN on NHANVIEN.PHG = PHONGBAN.MAPHG
GROUP BY TENPHG

--2a
SELECT DEAN.MADA, DEAN.TENDEAN, SUM(PHANCONG.THOIGIAN),
		CEILING(SUM(PHANCONG.THOIGIAN)),
		FLOOR(SUM(PHANCONG.THOIGIAN)),
		ROUND(SUM(PHANCONG.THOIGIAN), 2)
FROM DEAN
INNER JOIN CONGVIEC ON DEAN.MADA = CONGVIEC.MADA
INNER JOIN PHANCONG ON CONGVIEC.STT = PHANCONG.STT
GROUP BY DEAN.MADA, DEAN.TENDEAN

--2b
SELECT ROUND(AVG(LUONG),2) as N'Lương TB' FROM NHANVIEN
INNER JOIN PHONGBAN ON PHONGBAN.MAPHG = NHANVIEN.PHG
WHERE TENPHG like N'Nghiên cứu'

--2c
SELECT CONCAT(HONV,' ',TENLOT,' ',TENNV) as N'Họ và tên', LUONG as N'Lương TB' FROM NHANVIEN
WHERE LUONG >= (SELECT ROUND(AVG(LUONG),2) FROM NHANVIEN
INNER JOIN PHONGBAN ON PHONGBAN.MAPHG = NHANVIEN.PHG
WHERE TENPHG like N'Nghiên cứu')

--3a
SELECT UPPER(HONV), TENLOT, TENNV --chuyển thành chữ HOA
FROM NHANVIEN
GO
--
SELECT HONV, LOWER(TENLOT), TENNV --chuyển thành chữ THƯỜNG
FROM NHANVIEN
GO
--
SELECT MANV, COUNT(MA_NVIEN) FROM NHANVIEN, THANNHAN
WHERE NHANVIEN.MANV = THANNHAN.MA_NVIEN
GROUP BY MANV
GO

--3b
SELECT MANV, HONV, TENLOT, TENNV, DCHI, COUNT(MA_NVIEN) FROM NHANVIEN, THANNHAN
WHERE NHANVIEN.MANV = THANNHAN.MA_NVIEN
GROUP BY MANV, HONV, TENLOT,TENNV, DCHI
GO
--
SELECT MANV, HONV, TENLOT, TENNV, DCHI, COUNT(MA_NVIEN) FROM NHANVIEN, THANNHAN
WHERE NHANVIEN.MANV = THANNHAN.MA_NVIEN
GROUP BY MANV, HONV, TENLOT,TENNV, DCHI
HAVING COUNT(MA_NVIEN) > 2
GO
--
SELECT MANV, UPPER(HONV) as 'HONV', LOWER(TENLOT) as 'TENLOT', TENNV, DCHI, COUNT(MA_NVIEN) as 'SoLuongNV'
FROM NHANVIEN, THANNHAN
WHERE NHANVIEN.MANV = THANNHAN.MA_NVIEN
GROUP BY MANV, HONV, TENLOT,TENNV, DCHI
HAVING COUNT(MA_NVIEN) > 2
GO

--3c
SELECT MANV,
UPPER(HONV) AS 'HONV',
LOWER(TENLOT) AS 'TENLOT',
LOWER(LEFT(TENNV,1)) + UPPER(SUBSTRING(TENNV,2,1)) + LOWER(SUBSTRING(TENNV,3,LEN(TENNV)-2)) AS 'TENNV',
DCHI, COUNT(MA_NVIEN) FROM NHANVIEN, THANNHAN
WHERE NHANVIEN.MANV = THANNHAN.MA_NVIEN
GROUP BY MANV, HONV, TENLOT,TENNV, DCHI
HAVING COUNT(MA_NVIEN) > 2
GO

--3d
SELECT MANV,
SUBSTRING(DCHI,CHARINDEX(' ',DCHI)+ 1, CHARINDEX(',',DCHI) - (CHARINDEX(' ',DCHI) + 1)),
COUNT(MA_NVIEN) FROM NHANVIEN, THANNHAN
WHERE NHANVIEN.MANV = THANNHAN.MA_NVIEN
GROUP BY MANV, DCHI
HAVING COUNT(MA_NVIEN) > 2