/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab7;

import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NGUYEN THI THU NGHIA
 */
public class View_Profile extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form View
     */
    private Profile_Service service = new Profile_Service();
    private DefaultTableModel mol = new DefaultTableModel();
    private int index = -1;

    public View_Profile() {
        initComponents();
        this.setLocationRelativeTo(null);
        cbo_Quequan.removeAllItems();
        cbo_Quequan.addItem("Hà Nội");
        cbo_Quequan.addItem("HCM");
        cbo_Quequan.addItem("Bắc Ninh");
        cbo_Quequan.addItem("Đà Nẵng");
        this.fillToTable(service.getAll());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lbl_Profile = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        txtThunhap = new javax.swing.JTextField();
        rdoA = new javax.swing.JRadioButton();
        rdoB = new javax.swing.JRadioButton();
        rdoAB = new javax.swing.JRadioButton();
        rdoO = new javax.swing.JRadioButton();
        cbo_Quequan = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Profile = new javax.swing.JTable();
        btnSave = new javax.swing.JButton();
        btnSapxep = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnMoFile = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_Profile.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_Profile.setForeground(new java.awt.Color(0, 0, 255));
        lbl_Profile.setText("PROFILE    ");

        jLabel2.setText("HỌ TÊN");

        jLabel3.setText("THU NHẬP");

        jLabel4.setText("NHÓM MÁU");

        jLabel5.setText("QUÊ QUÁN");

        buttonGroup1.add(rdoA);
        rdoA.setText("A");

        buttonGroup1.add(rdoB);
        rdoB.setText("B");

        buttonGroup1.add(rdoAB);
        rdoAB.setSelected(true);
        rdoAB.setText("AB");

        buttonGroup1.add(rdoO);
        rdoO.setText("O");

        cbo_Quequan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tbl_Profile.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_Profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_ProfileMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_Profile);

        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnSapxep.setText("SẮP XẾP");
        btnSapxep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSapxepActionPerformed(evt);
            }
        });

        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnMoFile.setText("MỞ FILE");
        btnMoFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoFileActionPerformed(evt);
            }
        });

        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnTimKiem.setText("TÌM KIẾM THEO NHÓM MÁU");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSave)
                                    .addComponent(btnDelete))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSapxep)
                                    .addComponent(btnMoFile)))
                            .addComponent(btnReset)
                            .addComponent(btnTimKiem)))
                    .addComponent(lbl_Profile)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtThunhap, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdoA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdoB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdoAB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdoO))
                            .addComponent(cbo_Quequan, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lbl_Profile)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtThunhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rdoA)
                    .addComponent(rdoB)
                    .addComponent(rdoAB)
                    .addComponent(rdoO))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbo_Quequan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSave)
                            .addComponent(btnSapxep))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDelete)
                            .addComponent(btnMoFile))
                        .addGap(18, 18, 18)
                        .addComponent(btnReset)
                        .addGap(18, 18, 18)
                        .addComponent(btnTimKiem)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_ProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_ProfileMouseClicked
        // TODO add your handling code here:
        index = tbl_Profile.getSelectedRow();
        this.showDetails();
    }//GEN-LAST:event_tbl_ProfileMouseClicked

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        this.clearForm();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnSapxepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSapxepActionPerformed
        // TODO add your handling code here:
        service.sx(service.getAll());
        this.fillToTable(service.getAll());
    }//GEN-LAST:event_btnSapxepActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        index = tbl_Profile.getSelectedRow();
        JOptionPane.showMessageDialog(this, service.deletePr(index));
        this.fillToTable(service.getAll());
        this.clearForm();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        String nhom;
        nhom = JOptionPane.showInputDialog(this, "Mời bạn nhập nhóm máu cần tìm:");
        service.findMau(nhom);
        this.fillToTable(service.findMau(nhom));
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        index = tbl_Profile.getSelectedRow();
        if (index != -1) {
            JOptionPane.showMessageDialog(this, service.updatePr(index, this.readForm()));
        } else {
            JOptionPane.showMessageDialog(this, service.addPr(this.readForm()));
        }
        this.fillToTable(service.getAll());
        
        service.exportToFile(service.getAll(), "nghianehh.txt");
        this.clearForm();

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnMoFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoFileActionPerformed
        // TODO add your handling code here:
        JFileChooser jc = new JFileChooser();
        int chon = jc.showOpenDialog(null);
        if (chon == 0) {
            String path = jc.getSelectedFile().getPath();
            JOptionPane.showMessageDialog(this, service.openFile(path));
            if (service.openFile(path).contains("thành công")) {
                this.fillToTable(service.getAll());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn file");
        }

    }//GEN-LAST:event_btnMoFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_Profile().setVisible(true);
                View_Profile m = new View_Profile();//tạo đối tượng của form
                m.setVisible(true);//hiện ra form
                Thread th = new Thread(m);
                th.start();
            }
        });
    }

    public void fillToTable(List<Profile> list) {
        mol = (DefaultTableModel) tbl_Profile.getModel();
        mol.setRowCount(0);
        for (Profile pr : list) {
            mol.addRow(pr.toDataRow());
        }
    }

    public void showDetails() {
        Profile p = service.getAll().get(index);
        txtHoTen.setText(p.getTen());
        txtThunhap.setText(String.valueOf(p.getThuNhap()));
        if (p.getNhomMau().equalsIgnoreCase("A")) {
            rdoA.setSelected(true);
        } else if (p.getNhomMau().equalsIgnoreCase("B")) {
            rdoB.setSelected(true);
        } else if (p.getNhomMau().equalsIgnoreCase("AB")) {
            rdoAB.setSelected(true);
        } else {
            rdoO.setSelected(true);
        }
        cbo_Quequan.setSelectedItem(p.getQueQuan());
    }

    Profile readForm() {
        String ten, nhomMau, que;
        double thuNhap;
        ten = txtHoTen.getText();
        thuNhap = Double.parseDouble(txtThunhap.getText());
        if (rdoA.isSelected()) {
            nhomMau = "A";
        } else if (rdoB.isSelected()) {
            nhomMau = "B";
        } else if (rdoAB.isSelected()) {
            nhomMau = "AB";
        } else {
            nhomMau = "O";
        }
        que = cbo_Quequan.getSelectedItem().toString();
        return new Profile(ten, nhomMau, que, thuNhap);
    }

    public void clearForm() {
        txtHoTen.setText("");
        txtThunhap.setText("");
        cbo_Quequan.setSelectedItem(0);
        rdoAB.setSelected(true);
    }

    public void saveFile() {
        JFileChooser jc = new JFileChooser();
        int choose = jc.showSaveDialog(null);
        if (choose == 0) {
            String path = jc.getSelectedFile().getPath();
            JOptionPane.showMessageDialog(this, service.saveFile(path));
            mol.setRowCount(0);
        } else {
            JOptionPane.showMessageDialog(this, "Bạn không chọn save");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnMoFile;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSapxep;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbo_Quequan;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Profile;
    private javax.swing.JRadioButton rdoA;
    private javax.swing.JRadioButton rdoAB;
    private javax.swing.JRadioButton rdoB;
    private javax.swing.JRadioButton rdoO;
    private javax.swing.JTable tbl_Profile;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtThunhap;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        while (true) {
            String chu = lbl_Profile.getText();
            String c = chu.substring(0, 1);
            chu = chu.substring(1, chu.length());
            chu = chu + c;
            lbl_Profile.setText(chu);
            try {
                Thread.sleep(900);
            } catch (Exception e) {
                break;
            }
        }
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
