/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bai5;

import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NGUYEN THI THU NGHIA
 */
public class ViewMonHoc extends javax.swing.JFrame {

    /**
     * Creates new form ViewMonHoc
     */
    private Monhoc_Service service = new Monhoc_Service();
    private DefaultTableModel mol = new DefaultTableModel();

    public ViewMonHoc() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.fillToTable(service.getAll());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Monhoc = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Monhoc = new javax.swing.JTable();
        btn_Write = new javax.swing.JButton();
        btn_Read = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_Monhoc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_Monhoc.setText("QUẢN LÍ MÔN HỌC");

        tbl_Monhoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                " MÃ MÔN HỌC", "TÊN MÔN HỌC", "SỐ TÍN CHỈ"
            }
        ));
        jScrollPane1.setViewportView(tbl_Monhoc);

        btn_Write.setText(" WRITE");
        btn_Write.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_WriteActionPerformed(evt);
            }
        });

        btn_Read.setText("READ");
        btn_Read.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ReadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(btn_Write)
                        .addGap(27, 27, 27)
                        .addComponent(btn_Read))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(lbl_Monhoc, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Monhoc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Write)
                    .addComponent(btn_Read))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_WriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_WriteActionPerformed
        // TODO add your handling code here:
        //1. Ghi dữ liệu ra file
        //2. Nếu ghi thành công: thông báo: xóa bảng
        //3. Nếu không thành công: thông báo
        JFileChooser jc = new JFileChooser();
        int choose = jc.showSaveDialog(null);
        if (choose == 0) {//có lưu
            String path = jc.getSelectedFile().getPath();
            JOptionPane.showMessageDialog(this, service.writeFile(path));
            mol.setRowCount(0);//xóa bảng
        } else {//không lưu
            JOptionPane.showMessageDialog(this, "Bạn không chọn Save");
        }
    }//GEN-LAST:event_btn_WriteActionPerformed

    private void btn_ReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ReadActionPerformed
        // TODO add your handling code here:
        //1. Đọc từ file ra list
        //2. Nếu thành công: thông báo + đổ dữ liệu vào bảng
        //3. Nếu thất bại: thông báo
        JFileChooser jc = new JFileChooser();
        int chon = jc.showOpenDialog(null);
        if (chon == 0) {//có chọn file để đọc
            String path = jc.getSelectedFile().getPath();
            JOptionPane.showMessageDialog(this, service.readFile(path));
            if (service.readFile(path).contains("thành công")) {
                this.fillToTable(service.getAll());
            }
        } else
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn file");
    }//GEN-LAST:event_btn_ReadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMonHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMonHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMonHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMonHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewMonHoc().setVisible(true);
            }
        });
    }

    void fillToTable(List<MonHoc> list) {
        mol = (DefaultTableModel) tbl_Monhoc.getModel();
        mol.setRowCount(0);//xóa bảng cũ
        for (MonHoc m : list) {
            mol.addRow(m.toDataRow());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Read;
    private javax.swing.JButton btn_Write;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Monhoc;
    private javax.swing.JTable tbl_Monhoc;
    // End of variables declaration//GEN-END:variables
}
